// This file is part of the stenosaurus project.
//
// Copyright (C) 2014 Hesky Fisher <hesky.fisher@gmail.com>
//
// This library is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This library is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this library.  If not, see <http://www.gnu.org/licenses/>.
//
// This file defines keyboard related functionality for the Stenosaurus.
//
// See the .c file for implementation details.

#ifndef STENOSAURUS_FIRMWARE_KEYBOARD_H
#define STENOSAURUS_FIRMWARE_KEYBOARD_H

#include <stdint.h>
#include <stdbool.h>

typedef struct {
	uint8_t keycode;
	bool down;
} keyboard_event;

// From HID Usage tables chapter 10 (page 53):
// http://www.usb.org/developers/devclass_docs/Hut1_11.pdf
enum {
    KEY_RESERVED = 0x0,
    // We will treat zero as all keys up.
    KEY_RESET = 0,
    KEY_ERROR_ROLLOVER,
    KEY_POST_FAIL,
    KEY_ERROR_UNDEFINED,
    KEY_A,
    KEY_B,
    KEY_C,
    KEY_D,
    KEY_E,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_I,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_M,
    KEY_N,
    KEY_O,
    KEY_P,
    KEY_Q,
    KEY_R,
    KEY_S,
    KEY_T,
    KEY_U,
    KEY_V,
    KEY_W,
    KEY_X,
    KEY_Y,
    KEY_Z,
    KEY_1,  
    KEY_2,  
    KEY_3,  
    KEY_4,  
    KEY_5,  
    KEY_6,  
    KEY_7,  
    KEY_8,  
    KEY_9,  
    KEY_0,
    KEY_ENTER,
    KEY_ESCAPE,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_SPACE,
    KEY_MINUS,  
    KEY_EQUALS, 
    KEY_LEFT_BRACE,
    KEY_RIGHT_BRACE,
    KEY_BACKSLASH,  
    KEY_NUMBER,
    KEY_SEMICOLON,  
    KEY_QUOTE,  
    KEY_BACKQUOTE,
    KEY_COMMA,  
    KEY_PERIOD, 
    KEY_SLASH,  
    KEY_CAPS_LOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_F11,
    KEY_F12,
    KEY_PRINT_SCREEN,
    KEY_SCROLL_LOCK,
    KEY_PAUSE,
    KEY_INSERT,
    KEY_HOME,
    KEY_PAGE_UP,
    KEY_DELETE,
    KEY_END,
    KEY_PAGE_DOWN,
    KEY_RIGHT,
    KEY_LEFT,
    KEY_DOWN,
    KEY_UP,
    KEY_NUM_LOCK,
    KEYPAD_SLASH,
    KEYPAD_STAR,
    KEYPAD_MINUS,
    KEYPAD_PLUS,
    KEYPAD_ENTER,
    KEYPAD_1,  
    KEYPAD_2,  
    KEYPAD_3,  
    KEYPAD_4,  
    KEYPAD_5,
    KEYPAD_6,  
    KEYPAD_7,  
    KEYPAD_8,  
    KEYPAD_9,  
    KEYPAD_0,  
    KEYPAD_PERIOD,
    KEYPAD_BACKSLASH,
    KEY_APPLICATION,
    KEY_POWER,
    KEYPAD_EQUALS,
    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_F16,
    KEY_F17,
    KEY_F18,
    KEY_F19,
    KEY_F20,
    KEY_F21,
    KEY_F22,
    KEY_F23,
    KEY_F24,
    KEY_EXECUTE,
    KEY_HELP,
    KEY_MENU,
    KEY_SELECT,
    KEY_STOP,
    KEY_AGAIN,
    KEY_UNDO,
    KEY_CUT,
    KEY_COPY,
    KEY_PASTE,
    KEY_FIND,
    KEY_MUTE,
    KEY_VOLUME_UP,
    KEY_VOLUME_DOWN,
    KEY_LOCKING_CAPS_LOCK,
    KEY_LOCKING_NUM_LOCK,
    KEY_LOCKING_SCROLL_LOCK,
    KEYPAD_COMMA,
    KEYPAD_EQUAL_SIGN,
    KEY_INTERNATIONAL_1,
    KEY_INTERNATIONAL_2,
    KEY_INTERNATIONAL_3,
    KEY_INTERNATIONAL_4,
    KEY_INTERNATIONAL_5,
    KEY_INTERNATIONAL_6,
    KEY_INTERNATIONAL_7,
    KEY_INTERNATIONAL_8,
    KEY_INTERNATIONAL_9,
    KEY_LANG_1,
    KEY_LANG_2,
    KEY_LANG_3,
    KEY_LANG_4,
    KEY_LANG_5,
    KEY_LANG_6,
    KEY_LANG_7,
    KEY_LANG_8,
    KEY_LANG_9,
    KEY_ALT_ERASE,
    KEY_SYS_REQ,
    KEY_CANCEL,
    KEY_CLEAR,
    KEY_PRIOR,
    KEY_RETURN,
    KEY_SEPARATOR,
    KEY_OUT,
    KEY_OPER,
    KEY_CLEAR_AGAIN,
    KEY_CR_SEL_PROPS,
    KEY_EX_SEL,

    KEYPAD_00 = 0xb0,
    KEYPAD_000,
    KEY_THOUSANDS,
    KEY_DECIMAL,
    KEY_CURRENCY_UNIT,
    KEY_CURRENCY_SUB_UNIT,
    KEYPAD_LEFT_BRACKET,
    KEYPAD_RIGHT_BRACKET,
    KEYPAD_LEFT_BRACE,
    KEYPAD_RIGHT_BRACE,
    KEYPAD_TAB,
    KEYPAD_BACKSPACE,
    KEYPAD_A,
    KEYPAD_B,
    KEYPAD_C,
    KEYPAD_D,
    KEYPAD_E,
    KEYPAD_F,
    KEYPAD_XOR,
    KEYPAD_CAP,
    KEYPAD_PERCENT,
    KEYPAD_LESS_THAN,
    KEYPAD_GREATER_THAN,
    KEYPAD_AMPERSAND,
    KEYPAD_DOUBLE_AMPERSAND,
    KEYPAD_BAR,
    KEYPAD_DOUBLE_BAR,
    KEYPAD_COLON,
    KEYPAD_HASH,
    KEYPAD_SPACE,
    KEYPAD_AT,
    KEYPAD_BANG,
    KEYPAD_MEMORY_STORE,
    KEYPAD_MEMORY_RECALL,
    KEYPAD_MEMORY_CLEAR,
    KEYPAD_MEMORY_ADD,
    KEYPAD_MEMORY_SUBTRACT,
    KEYPAD_MEMORY_MULTIPLY,
    KEYPAD_MEMORY_DIVIDE,
    KEYPAD_PLUS_MINUS,
    KEYPAD_CLEAR,
    KEYPAD_CLEAR_ENTRY,
    KEYPAD_BINARY,
    KEYPAD_OCTAL,
    KEYPAD_DECIMAL,
    KEYPAD_HEXADECIMAL,

    KEY_LEFT_CONTROL = 0xe0,
    KEY_CONTROL = KEY_LEFT_CONTROL,
    KEY_LEFT_SHIFT,
    KEY_SHIFT = KEY_LEFT_SHIFT,
    KEY_LEFT_ALT,
    KEY_ALT = KEY_LEFT_ALT,
    KEY_LEFT_GUI,
    KEY_GUI = KEY_LEFT_GUI,
    KEY_RIGHT_CONTROL,
    KEY_RIGHT_SHIFT,
    KEY_RIGHT_ALT,
    KEY_RIGHT_GUI,
};

// Modifier bit flags as defined for the boot keyboard.
enum {
	MOD_LEFT_CTRL = 0x01,
	MOD_CTRL = 0x01,
	MOD_LEFT_SHIFT = 0x02,
	MOD_SHIFT = 0x02,
	MOD_LEFT_ALT = 0x04,
	MOD_ALT = 0x04,
	MOD_LEFT_GUI = 0x08,
	MOD_GUI = 0x08,
	MOD_RIGHT_CTRL = 0x10,
	MOD_RIGHT_SHIFT = 0x20,
	MOD_RIGHT_ALT = 0x40,
	MOD_RIGHT_GUI = 0x80,
};

#endif // STENOSAURUS_FIRMWARE_KEYBOARD_H